//-----------------------------------------------------------------------------
//
// Copyright (C) 2021 Lucid Systems Pty Ltd - All Rights Reserved
//
//-----------------------------------------------------------------------------

#include <db/sql_module_harness.h>

//-----------------------------------------------------------------------------

namespace ds::db::sql
{

//-----------------------------------------------------------------------------

const sql_map_t sql_map =
{

//-----------------------------------------------------------------------------

{ "test.simple",

R"(
   SELECT 0
)"
},

//-----------------------------------------------------------------------------

{ "test.no_result",

R"(
   SELECT * FROM (VALUES(1, 'one')) AS T WHERE FALSE
)"
},

//-----------------------------------------------------------------------------

{ "test.create",

R"(
   CREATE TABLE Object
   (
      i8          SMALLSERIAL,
      i16         SMALLSERIAL,
      i32         SERIAL,
      i64         BIGSERIAL,
      u8          SMALLINT,
      u16         SMALLINT,
      u32         INTEGER,
      u64         BIGINT,
      f           REAL,
      d           DOUBLE PRECISION,
      hello       VARCHAR( 10 ),
      dt          DATE,
      tm          TIME( 3 ),
      dttm        TIMESTAMP,
      id          INTEGER GENERATED BY DEFAULT AS IDENTITY
   )
)"
},

//-----------------------------------------------------------------------------

{ "test.batch",

R"(
   CREATE TABLE T1 (
      field INTEGER
   );

   CREATE TABLE T2 (
      field INTEGER
   );
)"
},

//-----------------------------------------------------------------------------

{ "test.insert",

R"(
   INSERT INTO Object
   (
      i8,
      i16,
      i32,
      i64,
      u8,
      u16,
      u32,
      u64,
      f,
      d,
      hello,
      dt,
      tm,
      dttm
   )
   VALUES ( $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14 )
)"
},

//-----------------------------------------------------------------------------

{ "test.insert_id",

R"(
   INSERT INTO Object
   (
      i8,
      i16,
      i32,
      i64,
      u8,
      u16,
      u32,
      u64,
      f,
      d,
      hello,
      dt,
      tm,
      dttm
   )
   VALUES ( $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14 )
   RETURNING id
)"
},

//-----------------------------------------------------------------------------


{ "test.result",

R"(
   SELECT u64 FROM Object WHERE hello = $1
)"
},

//-----------------------------------------------------------------------------

{ "test.results",

R"(
   SELECT i8,
          i16,
          i32,
          i64,
          u8,
          u16,
          u32,
          u64,
          f,
          d,
          hello,
          dt,
          tm,
          dttm
      FROM Object ORDER BY hello
)"
},

//-----------------------------------------------------------------------------

{ "test.num_rows",

R"(
   SELECT COUNT( * ) FROM Object
)"
},

//-----------------------------------------------------------------------------

{ "test.del_rows",

R"(
   DELETE FROM Object
)"
},

//-----------------------------------------------------------------------------

{ "test.named",

R"(
   INSERT INTO Object
   (
      i8,
      i16,
      i32,
      i64,
      u8,
      u16,
      u32,
      u64,
      f,
      d,
      hello,
      dt,
      tm,
      dttm
   )
   VALUES
   (
      :i8,
      :i16,
      :i32,
      :i64,
      :u8,
      :u16,
      :u32,
      :u64,
      :float,
      :double,
      :string,
      :date,
      :time,
      :datetime
   )
)"
},

//-----------------------------------------------------------------------------

{ "test.bad_sql",

R"(
   THIS IS BAD SQL
)"
},

//-----------------------------------------------------------------------------

{ "test.create_blob",

R"(
   CREATE TABLE Object
   (
      data        BYTEA
   )
)"
},

//-----------------------------------------------------------------------------

{ "test.insert_blob",

"INSERT INTO Object VALUES( $1 )"
},

//-----------------------------------------------------------------------------

{ "test.select_blob",

"SELECT * FROM Object"
},

//-----------------------------------------------------------------------------

{ "test.type",

"postgresql"
},
};

//-----------------------------------------------------------------------------

const char module_type[] = "postgresql";

//-----------------------------------------------------------------------------

}
